# GitHub Actions Workflow for Autonomous AiGentsy Execution
# 
# This workflow runs every hour and triggers autonomous discovery + execution
# 
# Setup:
# 1. Create this file in your repo as: .github/workflows/autonomous-execution.yml
# 2. Commit and push to GitHub
# 3. GitHub will automatically start running it every hour
#
# Manual Testing:
# - Go to Actions tab in GitHub
# - Click "Autonomous AiGentsy Execution"
# - Click "Run workflow"

name: Autonomous AiGentsy Execution

on:
  # Runs every hour on the hour
  schedule:
    - cron: '0 * * * *'
  
  # Allows manual triggering from GitHub UI
  workflow_dispatch:
    inputs:
      max_executions:
        description: 'Max executions to run'
        required: false
        default: '5'
      auto_approve_aigentsy:
        description: 'Auto-approve AiGentsy opportunities'
        required: false
        default: 'false'

jobs:
  autonomous-execution:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run Autonomous Discovery and Execution
        run: |
          # Set max executions (from input or default to 5)
          MAX_EXEC="${{ github.event.inputs.max_executions || '5' }}"
          AUTO_APPROVE="${{ github.event.inputs.auto_approve_aigentsy || 'false' }}"
          
          # Call the autonomous execution endpoint
          curl -X POST \
            "https://aigentsy-ame-runtime.onrender.com/execution/discover-and-execute?auto_approve_user=true&auto_approve_aigentsy=$AUTO_APPROVE&max_executions=$MAX_EXEC" \
            -H "Content-Type: application/json" \
            -o response.json
          
          # Show response
          echo "Response:"
          cat response.json | jq '.'
          
          # Check if successful
          if [ $(cat response.json | jq -r '.ok') = "true" ]; then
            echo "✅ Autonomous execution completed successfully"
            
            # Show stats
            DISCOVERED=$(cat response.json | jq -r '.discovery.total_opportunities')
            EXECUTED=$(cat response.json | jq -r '.executions.count')
            
            echo "📊 Discovered: $DISCOVERED opportunities"
            echo "⚡ Executed: $EXECUTED opportunities"
          else
            echo "❌ Autonomous execution failed"
            exit 1
          fi
      
      - name: Get Execution Stats
        if: success()
        run: |
          # Get current stats
          curl -s https://aigentsy-ame-runtime.onrender.com/execution/stats \
            -H "Content-Type: application/json" \
            | jq '.'
      
      - name: Check System Health (Daily)
        # Only run health check once per day (at midnight UTC)
        if: success() && github.event.schedule == '0 0 * * *'
        run: |
          echo "🔍 Running daily system health check..."
          
          curl -s https://aigentsy-ame-runtime.onrender.com/execution/health/quick \
            -H "Content-Type: application/json" \
            | jq '.'
      
      - name: Notify on Failure
        if: failure()
        run: |
          echo "❌ Autonomous execution workflow failed"
          echo "Check logs above for details"
          # Add notification here (Slack, email, etc.)
